name: Build ThinkNode M1 Companion (CZ repeat)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v6

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Build Firmware
        env:
          FIRMWARE_VERSION: v1.17.1-czrepeat
        run: /usr/bin/env bash build.sh build-firmware ThinkNode_M1_companion_radio_ble

      - name: Upload Firmware
        uses: actions/upload-artifact@v7
        with:
          name: ThinkNode_M1_companion_radio_ble-czrepeat
          path: out
